version: "2.1"

services:
  database:
    build: 
       context: ./database
    image: atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: atsea
    ports:
      - "5432:5432" 



  appserver:
    build:
       context: app
       dockerfile: Dockerfile-dev
    image: atsea_app
    ports:
      - "8080:8080"
      - "5005:5005"

